# Generated by Django 3.2.7 on 2023-01-23 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSentoVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sento.sento', verbose_name='銭湯')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': '銭湯訪問履歴',
                'db_table': 'user_sento_visits',
            },
        ),
    ]
