import Head from 'next/head'
import {Inter} from '@next/font/google'
import styles from '@/styles/Home.module.css'
import React, {createContext, useEffect, useState} from "react";
import {MapPage} from 'components/map_home'
import {Login} from 'components/login'
import axios from "axios";
import {Logout} from "@/components/logout";
import {Signup} from "@/components/signup";

const inter = Inter({subsets: ['latin']})

export default function Home() {
  const [userId, setUserId] = useState(0)
  const [name, setName] = useState('')
  const [visitedSento, setVisitedSento] = useState({})

  useEffect(() => {
    getUserProfile()
    getUserVisitedSentos()
  }, [name])

  const getUserProfile = () => {
    try {
      axios.get('http://localhost:8000/api/auth/users/me/', {
        headers: {
          Authorization: `JWT ${localStorage.getItem('access')}`
        }
      })
        .then((res) => {
          setUserId(res.data.id)
          setName(res.data.name)
        })
        .catch((err) => {
        setName('')
      })
    } catch (err) {
      setName('')
    }
  }

  const getUserVisitedSentos = () => {
    try {
      axios.get('http://localhost:8000/api/v1/sento/visits/', {
        headers: {
          Authorization: `JWT ${localStorage.getItem('access')}`
        }
      })
        .then((res) => {
          setVisitedSento(res.data)
        })
        .catch((err) => {
          console.error(err)
        })
    } catch (err) {
      console.error(err)
    }
  }

  return (
    <>
      <Head>
        <title>銭湯ログ</title>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <main className={styles.main}>
        {name === '' ? (
          <>
            <Login/>
            <Signup />
          </>
        ) : (
          <Logout name={name} />
        )}
        <MapPage userId={userId} visitedSento={visitedSento} />
      </main>
    </>
  )
}
